### ISSUE TITLE
uni+ eslint Running compilation errors

### ISSUE THREAD

**Issue by wanshouqing** [SharePoint/sp-dev-solutions#237]
当前项目编译模式：非自定义组件模式。编译模式差异见：https://ask.dcloud.net.cn/article/35843

 ERROR  Error: Cannot find module '@dcloudio/webpack-uni-mp-loader/lib/style.js'
Error: Cannot find module '@dcloudio/webpack-uni-mp-loader/lib/style.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._resolveFilename (F:\work\zhifubao_chat\zmn-mini\node_modules\module-alias\index.js:49:29)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at Object.chainWebpack (F:\work\zhifubao_chat\zmn-mini\node_modules\@dcloudio\vue-cli-plugin-uni\lib\mp.js:186:23)
    at api.chainWebpack.webpackConfig (F:\work\zhifubao_chat\zmn-mini\node_modules\@dcloudio\vue-cli-plugin-uni\index.js:617:21)
    at webpackChainFns.forEach.fn (F:\work\zhifubao_chat\zmn-mini\node_modules\@vue\cli-service\lib\Service.js:227:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (F:\work\zhifubao_chat\zmn-mini\node_modules\@vue\cli-service\lib\Service.js:227:26)
    at PluginAPI.resolveChainableWebpackConfig (F:\work\zhifubao_chat\zmn-mini\node_modules\@vue\cli-service\lib\PluginAPI.js:128:25)
    at module.exports (F:\work\zhifubao_chat\zmn-mini\node_modules\@vue\cli-service\lib\commands\build\resolveAppConfig.js:2:22)
    at build (F:\work\zhifubao_chat\zmn-mini\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:66:88)
    at api.registerCommand (F:\work\zhifubao_chat\zmn-mini\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:38:11)
    at Service.run (F:\work\zhifubao_chat\zmn-mini\node_modules\@vue\cli-service\lib\Service.js:221:12)
    at Object.<anonymous> (F:\work\zhifubao_chat\zmn-mini\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! c@0.1.0 dev:mp-alipay: `cross-env NODE_ENV=development UNI_PLATFORM=mp-alipay vue-cli-service uni-build --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the c@0.1.0 dev:mp-alipay script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2019-07-26T06_05_16_384Z-debug.log

**Comment by VesaJuvonen** [comment]
Closing due to lack of sufficient details to provide support.
