### ISSUE TITLE
react-search-refiners: not working out of the box

### ISSUE THREAD

**Issue by Peter-Ross-C** [SharePoint/sp-dev-solutions#56]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Webpart works out the box

#### Observed Behavior
So this may just be my lack of knowledge, but I'm getting some issues with react-search-refiners out of the box. When I run gulp serve and load the webpart in the SharePoint workbench, it returns an error `Cannot find module "."`. I'm using Node v8.15.0

It also is spitting out the following error:
`Warning - [webpack] 'dist':
./node_modules/log-utils/node_modules/ansi-colors/index.js
14:35-42 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
    at CommonJsRequireContextDependency.getWarnings (<Path>\sp-dev-solutions\solutions\ModernSearch\react-search-refiners\spfx\node_modules\webpack\lib\dependencies\CommonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (<Path>\sp-dev-solutions\solutions\ModernSearch\react-search-refiners\spfx\node_modules\webpack\lib\Compilation.js:694:24)
    at Compilation.finish (<Path>\sp-dev-solutions\solutions\ModernSearch\react-search-refiners\spfx\node_modules\webpack\lib\Compilation.js:552:9)
    at applyPluginsParallel.err (<Path>\sp-dev-solutions\solutions\ModernSearch\react-search-refiners\spfx\node_modules\webpack\lib\Compiler.js:506:17)
    at <Path>\sp-dev-solutions\solutions\ModernSearch\react-search-refiners\spfx\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (<Path>\sp-dev-solutions\solutions\ModernSearch\react-search-refiners\spfx\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (<Path>\sp-dev-solutions\solutions\ModernSearch\react-search-refiners\spfx\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)`

#### Steps to Reproduce
npm install
gulp serve
Use SharePoint workbench (not local)

**Comment by FranckyC** [comment]
Hi @Peter-Ross-C, just in case, can you try to wipe out your _node_modules_ folder and _package-lock.json_ file and then retry?

**Comment by ryanjonhealy** [comment]
@Peter-Ross-C Copy the package.json from the repo and run `npm i` again. 
I saw some errors, the terminal  suggested `npm audit`, which I did and had the same issue.

**Comment by wobba** [comment]
@Peter-Ross-C still an issue or can we close this one?

**Comment by Peter-Ross-C** [comment]
Hi,

This can be closed. Deleting the node_modules folder, deleting package-lock.json and then reinstalling the packages seemed to work.

Kind Regards
Peter-Ross Cuthbert

________________________________
