### ISSUE TITLE
Can't run package-solution --ship on react-search-refiners

### ISSUE THREAD

**Issue by Kman1131** [SharePoint/sp-dev-solutions#82]
#### Category

- [x] Bug

#### Expected or Desired Behavior
Running from the spfx folder: npm install followed by gulp build --ship & gulp package-solution --ship should produce a build.

#### Observed Behavior
When just gulp build and gulp package-solution are used the package is generated successfully, with the addition of --ship, package-solution produces the following error:

Error - Error: The webparts manifests list is empty. Please ensure you have done a build and that your config file is pointed at the correct folder.
    at Object.createPackage [as default] (C:/Users/###/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/packageSolution/createPackage.js:25:19)
    at DestroyableTransform.gulp.src.pipe.through2.obj [as _flush] (C:/###/Documents/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/PackageSolutionTask.js:116:36)
    at DestroyableTransform.prefinish (C:/Users/###/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at prefinish (C:/Users/###/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (C:/Users/###/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (C:/Users/###/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (C:/Users/###/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (C:/Users/###/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
Error - Error: The webparts manifests list is empty. Please ensure you have done a build and that your config file is pointed at the correct folder.
    at Object.createPackage [as default] (C:/Users/###/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/packageSolution/createPackage.js:25:19)
    at DestroyableTransform.gulp.src.pipe.through2.obj [as _flush] (C:/Users/###/Documents/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/PackageSolutionTask.js:116:36)
    at DestroyableTransform.prefinish (C:/Users/###/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at prefinish (C:/Users/caleb.stone/Documents/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (C:/Users/###/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (C:/Users/###/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (C:/Users/###/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (C:/Users/###/SPFx-Webparts/ModernSearch/react-search-refiners/spfx/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
Error - 'package-solution' sub task errored after 70 ms 
 No manifests were found in '*.json'. Ensure a build has completed successfully and that paths.manifestsMatch is correct

#### Steps to Reproduce
clone
cd spfx
npm install
gulp build --ship
gulp package-solution --ship

**Comment by wobba** [comment]
@Kman1131 which SPFx version do you have installed? Latest code require v1.7.1.

**Comment by FranckyC** [comment]
@Kman1131 Did you run `gulp bundle --ship`? It seems not if I look at your steps

**Comment by Kman1131** [comment]
@wobba & @FranckyC Omg so sorry guys - 18hrs up, too much coffee and lack of sleep - then I start using commands I have never used before, please close and mark user as incompetent and amateur!

On another note - fantastic work on this lately, I have been using this since the early days and the solution has really progressed. Sorry to waste your time here guys.
